### ISSUE TITLE
[Feature]: onEvent

### ISSUE THREAD

**Issue by AlexanderARodin** [mahyarmirrashed/yaos#9]
it would be cool if the plugin sync might be optionally invoked by at least following Obsidian events:
- start up
- quit

Something like plugin **Shell commands** has. But much more simple.

It's not critical. But it would be nice.
Thnx anyway for the plugin 👍

**Comment by mahyarmirrashed** [comment]
Hi @AlexanderARodin , thank you for this suggestion. I think it's a wonderful idea!

I am thinking of maybe having it as toggle options for each Obsidian event. What are your thoughts on that?

**Comment by AlexanderARodin** [comment]
On a one hand, a few toggles for critical and wide used events will be enough to keep plugin easy and lightweight.
On the other hand, more options may give popularity increasing. Or decreasing. I don't know.

**Comment by mahyarmirrashed** [comment]
I think I'll just add the toggle buttons for both the `startUp` and `quit` events. I'll research that a bit more and update the ticket once it's done.

**Comment by mahyarmirrashed** [comment]
Got it 90% working. The problem is that there might not be a simple way to do `onLoad` and `onUnload` for detecting when a vault opens/closes. The stuff provided to me by the API seems to only be for enabling/disabling the plugin. I've asked the other Obsidian developers and will update if one of them knows a solution.

**Comment by mahyarmirrashed** [comment]
I did take a look at their implementation and took inspiration from it. That wasn't working as expected in my tests. Perhaps all vaults need to close for the commands to execute? But, I wouldn't integrate the feature if that was the case. Still waiting to hear back from the other Obsidian devs.

**Comment by mahyarmirrashed** [comment]
Hi @AlexanderARodin , sorry for no update on this. I have not heard back from the Obsidian community on this. I think the best way would be for the Obsidian team to properly develop the hook for plugins to trigger on the open/close vault properly rather than this method (which feels sort of bootleg). Let me know your thoughts. This would also make this feature implementation more solid.

**Comment by AlexanderARodin** [comment]
HNY n MC
